name: Assignment 1 CI

on:
  push:
    branches: [ "main" ]

jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .

  Build-and-push:
    runs-on: ubuntu-latest
    needs:  Clone-down
    permissions:
      packages: write
    steps:
      - name: Login to DockerHub
        run:  echo ${{ secrets.DOCKERHUB_SECRET }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_SECRET }}
      
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .      
            
      - name: Build and tag Docker image
        run:  docker build -t devops-1 .

      - name: Push Docker image to Dockerhub
        run:  docker push devops-1:latest


